apiVersion: apps/v1
kind: Deployment
metadata:
  name: tictac-v2-deployment
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: tic-tac-app
      version: v2
  template:
    metadata:
      labels:
        app: tic-tac-app
        version: v2
    spec:
      containers:
        - name: tic-tac-container
          image: 690109731501.dkr.ecr.us-east-1.amazonaws.com:v1.1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
